version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: daily
    assignees:
      - blaine-arcjet
      - e-moran
    reviewers:
      - blaine-arcjet
      - e-moran
