[package]
authors = ["The Arcjet team"]
categories = ["wasm"]
default-run = "gravity"
name = "arcjet-gravity"
version = "0.0.1"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/arcjet/gravity"
description = """
Gravity is a host generator for WebAssembly Components. It currently targets Wazero, a zero dependency WebAssembly runtime for Go.
""""

[[bin]]
name = "gravity"
path = "src/main.rs"

[dependencies]
clap = "=4.5.31"
genco = "=0.17.10"
wit-bindgen-core = "=0.35.0"
wit-component = "=0.220.0"
