[toolchain]
channel = "1.90.0"
components = [
    "rustc",
    "cargo",
    "rustfmt",
    "rust-std",
    "rust-analyzer",
    "clippy",
    "rust-src",
]
targets = [
    "wasm32-unknown-unknown",
    "wasm32-wasip1",
]
profile = "default"
