package arcjet:basic;

interface logger {
  debug: func(msg: string);
  info: func(msg: string);
  warn: func(msg: string);
  error: func(msg: string);
}

interface utils {
  uppercase: func(val: string) -> string;
}

world basic {
  import logger;
  import utils;

  record point {
    x: u32,
    y: u32,
  }

  export hello: func() -> result<string, string>;
  export primitive: func() -> bool;
  export optional-primitive: func(b: option<bool>) -> option<bool>;
  export result-primitive: func() -> result<bool, string>;

  export optional-string: func(s: option<string>) -> option<string>;
}
