package arcjet:example;

interface runtime {
  os: func() -> string;
  arch: func() -> string;

  get-u32: func() -> u32;

  puts: func(msg: string);
}

world example {
  import runtime;

  export hello: func() -> result<string, string>;
  export call-get-u32: func() -> u32;
}
