name: Rust build and test

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  gravity:
    name: Gravity tests
    runs-on: ubuntu-latest
    steps:
      # Environment security
      - name: Step Security
        uses: step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7618a84e # v2.10.4
        with:
          egress-policy: audit

      # Checkout
      # Most toolchains require checkout first
      - name: Checkout
        uses: actions/checkout@v4

      - name: "Setup Go (stable)"
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
        with:
          go-version: 'stable'

      - name: "Setup Go caches"
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-golang-

      - name: "Use Nightly Rust in rust-toolchain.toml"
        uses: actions-rust-lang/setup-rust-toolchain@9d7e65c320fdb52dcd45ffaa68deb6c02c8754d9 # v1.12.0

      # Workflow

      - name: cargo build
        run: cargo build --locked --verbose
        env:
          CARGO_TERM_COLOR: always

      - name: cargo test
        run: cargo test --locked --verbose
        env:
          CARGO_TERM_COLOR: always

      - name: go tests
        run: |
          go generate ./...
          go test ./...

